---
# Fail2ban Logrotate — Configure log rotation for Fail2ban log files.

# Archive Directory Setup
- name: Fail2ban | logrotate | Check if archive log directory exists
  become: true
  ansible.builtin.stat:
    path: "{{ fail2ban_logrotate_options.archive_directory_path }}"
  register: __fail2ban_archive_log_directory_stat

- name: Fail2ban | logrotate | Create archive log directory if needed
  become: true
  ansible.builtin.file:
    path: "{{ fail2ban_logrotate_options.archive_directory_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when:
    - not __fail2ban_archive_log_directory_stat.stat.exists

# Logrotate Configuration Deployment
- name: Fail2ban | logrotate | Deploy logrotate configuration file
  become: true
  ansible.builtin.template:
    src: "logrotate/{{ ansible_facts['os_family'] | lower }}/fail2ban.j2"
    dest: "{{ fail2ban_logrotate_config_path }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
